name: Update project structure
on: [workflow_dispatch]
jobs:
  autoUpdateProject:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5

      - name: Update project structure
        run: |
          pip install cruft
          cruft update -y

      - name: Get new template version
        run: |
          pip install jello
          # extract new cooiecutter template version
          echo "TEMPLATE_COMMIT=$(cat .cruft.json | jello -r "_['commit'][:8]")" >> $GITHUB_ENV

      # behaviour if PR already exists: https://github.com/marketplace/actions/create-pull-request#action-behaviour
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "chore: update project structure to ${TEMPLATE_COMMIT})"
          title: "[Cookiecutter] Auto-Update project structure"
          body: ""
          branch: "chore/cookiecutter-pypackage"
          delete-branch: true
