name: Update project structure
on: 
  pusth:
    branch: master
      - master

jobs:
  autoUpdateProject:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5

      - name: Install dependencies
        run: pip install cruft jello

      - name: Update project structure
        run: cruft update -y

      - name: Get new template version
        # extract new cooiecutter template version
        run: |
          echo "TEMPLATE_COMMIT=$(cat .cruft.json | jello -r "_['commit'][:8]")" >> $GITHUB_ENV

      - name: Test
        run: echo $TEMPLATE_COMMIT

      - name: Test2
        run: echo ${{ env.TEMPLATE_COMMIT}}

      # behaviour if PR already exists: https://github.com/marketplace/actions/create-pull-request#action-behaviour
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "chore: update project structure to ${ env.TEMPLATE_COMMIT}"
          title: "[Cookiecutter] Auto-Update project structure"
          body: ""
          branch: "chore/cookiecutter-pypackage"
          delete-branch: true
